# Generated by Django 4.0.1 on 2022-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faded_text', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('bold_text', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='Box_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Boxes')),
            ],
        ),
        migrations.CreateModel(
            name='Hot_Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('review', models.IntegerField()),
                ('img', models.ImageField(upload_to='Hot_Tour')),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='Team')),
            ],
        ),
        migrations.CreateModel(
            name='Wonder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Wonder')),
            ],
        ),
    ]
