# Generated by Django 4.0.1 on 2022-04-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot_tour',
            name='rating',
        ),
    ]
