# Generated by Django 4.0.1 on 2022-04-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
